# Generated by Django 4.2 on 2023-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='rank',
            new_name='team_member',
        ),
    ]
