# Generated by Django 4.2 on 2023-06-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_rank_skill_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
