# Generated by Django 4.1.5 on 2023-07-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
    ]
