# Generated by Django 4.2 on 2023-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
