# Generated by Django 4.2 on 2023-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_subscriber_options_mailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
