# Generated by Django 4.2 on 2023-06-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Services/cover/'),
        ),
        migrations.AddField(
            model_name='service',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='Services/front/'),
        ),
    ]
