# Generated by Django 4.2 on 2023-06-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_image_service_cover_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
