# Generated by Django 4.2 on 2023-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
