# Generated by Django 4.2 on 2023-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimony_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
