# Generated by Django 4.2 on 2023-06-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='name',
        ),
        migrations.AddField(
            model_name='testimony',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
