# Generated by Django 4.2 on 2023-06-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_testimony_image_remove_testimony_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ('-rating',)},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='instagram',
            new_name='youtube',
        ),
    ]
