# Generated by Django 4.1.5 on 2023-07-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_period_assignmentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
