# Generated by Django 4.1.5 on 2023-07-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignmentorder_files_projectperiod_projectorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentorder',
            name='files',
        ),
        migrations.RemoveField(
            model_name='projectorder',
            name='files',
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.projectorder')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentorder')),
            ],
        ),
    ]
