# Generated by Django 4.1.5 on 2023-07-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_remove_assignmentorder_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('mpesa_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='assignments.assignmentorder')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='assignments.projectorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
