# Generated by Django 4.1.5 on 2023-07-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='assignments.assignmentorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='assignments.projectorder'),
        ),
    ]
