# Generated by Django 4.1.5 on 2023-07-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_payment_assignment_alter_payment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['unit']},
        ),
        migrations.AlterField(
            model_name='assignmentfiles',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignmentorder'),
        ),
        migrations.AlterField(
            model_name='assignmentorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.projectorder'),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
