# Generated by Django 4.1.5 on 2023-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_period_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
