# Generated by Django 4.1.5 on 2023-08-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_projectperiod_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='assignments.assignmentorder')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='assignments.projectorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
