# Generated by Django 5.0.2 on 2024-03-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_rename_update_at_note_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created_at',)},
        ),
    ]
