# Generated by Django 4.1.5 on 2023-07-04 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='count',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='trial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to=settings.AUTH_USER_MODEL),
        ),
    ]
