# Generated by Django 4.1.5 on 2023-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_count_trial_number_alter_trial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='description',
            field=models.TextField(),
        ),
    ]
