# Generated by Django 4.1.5 on 2023-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_generatedimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
