# Generated by Django 4.2 on 2023-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_generatedimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
