# Generated by Django 4.1.5 on 2023-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_generatedimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
