# Generated by Django 4.1.5 on 2023-07-09 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_generatedimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image_url',
            field=models.URLField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
