# Generated by Django 4.1.5 on 2023-07-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0009_alter_generatedimage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='user',
        ),
        migrations.CreateModel(
            name='ImageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='ai.imagedescription'),
        ),
    ]
