# Generated by Django 4.1.5 on 2023-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_remove_generatedimage_user_imagedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedescription',
            name='size',
            field=models.CharField(default='1024x1024', max_length=100),
        ),
    ]
