# Generated by Django 4.1.5 on 2023-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_imagedescription_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedescription',
            name='initial_number_of_images',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
