# Generated by Django 4.1.5 on 2023-07-24 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_areachoice_levelchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedideas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idearequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedideas',
            name='project_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
