# Generated by Django 4.1.5 on 2023-07-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_generatedideas_created_at_idearequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedideas',
            old_name='project_details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='generatedideas',
            old_name='idea',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='generatedideas',
            old_name='project_title',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai.generatedideas')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
