# Generated by Django 4.1.5 on 2023-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_rename_request_generatedideas_idea_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelchoice',
            name='charge_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='e.g 1,1.2', max_digits=3),
        ),
        migrations.AlterField(
            model_name='levelchoice',
            name='title',
            field=models.CharField(help_text='e.g, High School, Degree, Masters, PHD', max_length=50),
        ),
    ]
