# Generated by Django 4.1.5 on 2023-07-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_levelchoice_charge_rate_alter_levelchoice_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='idea',
        ),
        migrations.AddField(
            model_name='payment',
            name='idea_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai.idearequest'),
            preserve_default=False,
        ),
    ]
