# Generated by Django 4.1.5 on 2023-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_payment_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='idearequest',
            name='number_of_ideas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
