# Generated by Django 4.1.5 on 2023-07-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_idearequest_number_of_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idea_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='ai.idearequest'),
        ),
    ]
