# Generated by Django 4.1.5 on 2023-07-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0022_alter_payment_idea_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='idearequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idea_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ai.idearequest'),
            preserve_default=False,
        ),
    ]
