# Generated by Django 4.1.5 on 2023-07-27 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0023_idearequest_is_active_alter_payment_idea_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='idearequest',
            name='refered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
