# Generated by Django 4.1.5 on 2023-08-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0025_alter_idearequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelchoice',
            options={'ordering': ['craeted_at'], 'verbose_name': 'Level Choice', 'verbose_name_plural': 'Level Choices'},
        ),
        migrations.RemoveField(
            model_name='generatedideas',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generatedideas',
            name='title',
        ),
        migrations.CreateModel(
            name='IdeaPoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_category', to='ai.levelchoice')),
                ('subject_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_category', to='ai.areachoice')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='ai.ideapoolcategory')),
            ],
        ),
        migrations.AddField(
            model_name='generatedideas',
            name='idea',
            field=models.ManyToManyField(blank=True, to='ai.ideapool'),
        ),
    ]
