# Generated by Django 4.1.5 on 2023-08-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0026_alter_levelchoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedideas',
            name='idea',
        ),
        migrations.AddField(
            model_name='generatedideas',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_ideas', to='ai.ideapool'),
            preserve_default=False,
        ),
    ]
