# Generated by Django 4.2 on 2023-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
